### ISSUE TITLE
Questions about modifying the Lua core for OpenComputers

### ISSUE THREAD

**Issue by RobertCochran** [MightyPirates/OC-Natives#2]
I'm planning on modifying the Lua core to support per-coroutine memory
information in OpenComputers.

I have a few questions, mostly about style.
1. First off, its not a bad thing to do this directly in the C code vs doing it
   in the Scala/Java code, is it? I'm not familiar with the Scala/Java side, but I
   have the feeling that the Scala/Java side does not see the allocations that the
   Lua interpretter makes, necessitating modifying the C code.
2. Would it be alright to 'extend' an existing library? Since this patch is for
   coroutine stuff, I would naturally put the function in the coroutine library,
   rather than try to find a place to cram it into an OpenComputers library.
3. Where should the commits go? Technically, the code is within the Eris sub-repo,
   but the code is meant specifically for OpenComputers and has no point outside of
   it.

This last one is more of a 'what is your opinion' -
1. What should happen in LuaJ? Since this function is meant to be used by OSes for
   memory management purposes, it's pointless in the unconstrainted LuaJ
   environment. I'm not sure what would be a reasonable return value would be, or
   if it should exist at all under LuaJ. For reference, in LuaJ,
   (computer.freeMemory() == computer.totalMemory() / 2).

Thanks for your time.

**Comment by fnuecke** [comment]
There's a lot of overlap to those questions, and the name of the intersect is "JNLua" ;-)

Lua's memory limits are enforced using a custom allocator method, which [is implemented in the JNLua fork](https://github.com/fnuecke/jnlua/blob/eris/jnlua/src/main/c/jnlua.c#L200-L248) used for OpenComputers. So I'd say it'd make sense to hook into that. In particular, this should be implemented fully in C, due to the high marshaling costs. For exposing the per-coroutine use, I'd suggest further additional method in the Java side of JNLua. For exposing it to OpenComputers's Lua implementations, I'd suggest adding it to the `computer` library; something like `computer.usedMemory([coroutine])` (defaulting to the _global_ used memory when no coroutine is given). I dislike modifying the standard libraries (calling it `os.sleep` was a stupid mistake on my part).

So the stuff for the C implementation and JNLua Java side would go into the fork repo. After building the natives and bundling the JNLua JAR those'd go into the OC repo, as would the exposing to Lua in OC of course.

As for LuaJ... right... I forgot that was even what was being returned by free/total memory. Probably just return the same as global freeMemory then, for symmetry (i.e. also half total).
